sudo: required
services:
  - docker

before_install:
  - docker build -t 1man/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 1man/react-test npm run test-coverage -- --coverage

after_success:
  - docker build -t 1man/multi-client ./client
  - docker build -t 1man/multi-nginx ./nginx
  - docker build -t 1man/multi-server ./server
  - docker build -t 1man/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 1man/multi-client
  - docker push 1man/multi-nginx
  - docker push 1man/multi-server
  - docker push 1man/multi-worker
